#+title: Greg Newman's Emacs Configuration
* My emacs config is written in org-babel, using literate programming
a for better documented emacs config.
** TODOs
- Add Anaconda for Python development
- Setup Org-mode
** Packages I have installed
- Solarized
- Zenburn
- Org-mode
- Virtualenvwrapper
- Elpy
- Company
** Setup package manager for emacs modes.  After looking at the options
I'm using Marmalade.  I don't want to be using bleeding edge which it
seems MELPA uses since it links directly the git repos.
#+BEGIN_src emacs-lisp :tangle yes
(require 'package)
;; Add the original Emacs Lisp Package Archive
(add-to-list 'package-archives
             '("elpa" . "http://tromey.com/elpa/"))
;; Add the user-contributed repository
(add-to-list 'package-archives
             '("marmalade" . "http://marmalade-repo.org/packages/"))
(add-to-list 'package-archives
	     '("melpa" . "http://melpa.milkbox.net/packages/"))
#+end_src
** Add the Zenburn theme and consider the custom themes safe.
#+BEGIN_src emacs-lisp :tangle yes
(setq custom-safe-themes t)
(package-initialize)
(load-theme 'zenburn)
#+end_src
** Backups in the current directory are annoying.  Let's move those to
a central location.  I'm not worried about disk space here.
#+BEGIN_src emacs-lisp :tangle yes
(setq backup-directory-alist '(("." . "~/.emacs.d/backups")))
(setq delete-old-versions -1)
(setq version-control t)
(setq vc-make-backup-files t)
(setq auto-save-file-name-transforms '((".*" "~/.emacs.d/auto-save-list/" t)))
#+end_src

** Windows Configuration
Hide things when emacs starts up, namely the tooltips, toolbar dn scrollbar.
#+BEGIN_src emacs-lisp :tangle yes
(when window-system
  (tooltip-mode -1)
  (tool-bar-mode -1)
  (menu-bar-mode 1)
  (scroll-bar-mode -1))
#+end_src
** Line numbers, gutters, line highlighting and default tabs, column markers
Show line number in the left gutter and highlight current line
Set default tabs to 4.  Highlight line.  There are a number of
packages for highlighting the current line but hi-line is already
included and works fine.  No more cruft than needed.
Mark the column at 80 for python.
#+BEGIN_src emacs-lisp :tangle yes
(global-linum-mode 1)
(setq column-number-mode  t)
(global-hl-line-mode 1)
(setq-default default-tab-width 4)
(require 'whitespace)
(setq whitespace-style '(face empty tabs lines-tail trailing))
(global-whitespace-mode t)
#+end_src
** I hate that emacs opens at the top left of my screen and a tiny
frame.  SEt a default width, height and location
#+BEGIN_src emacs-lisp :tangle yes
(setq initial-frame-alist '((top . 50)
                            (left . 200)
                            (width . 100)
                            (height . 40)))
#+end_src
** Python / Elpy
Starting with just Elpy.  As I feel I need to replicate the setup
I had with WingIDE I'll modify this.  I tried to setup Anaconda but there's
inherent problems with my El Capitan homebrew setup of python and pip that
prevents it from running in the Emacs GUI.  It works fine in terminal.  Trying
out Elpy to see if that has issues.  I love the fact that Elpy is on 
readthedocs.org!!
- Documentation: http://elpy.readthedocs.org/en/latest/ide.html
#+BEGIN_src emacs-lisp :tangle yes
(package-initialize)
(elpy-enable)
;; Fixing a key binding bug in elpy
(define-key yas-minor-mode-map (kbd "C-c k") 'yas-expand)
;; Fixing another key binding bug in iedit mode
(define-key global-map (kbd "C-c o") 'iedit-mode)
#+end_src

** IDO
Because it saves time
#+BEGIN_src emacs-lisp :tangle yes
;; IDO rules
(require 'ido)
(ido-mode t)
(setq ido-enable-flex-matching t)
#+end_src
